name: dataLoader
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - pathlib
  - pytest
  - pytest-mock
  - pytest-cov
  - pandera
  - pandera-mypy
  - pydantic=1.10
  - python-decouple
  - pip
  - pip:
    - mariadb>=1.1