name: dataLoader
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - pathlib
  - pytest
  - pytest-mock
  - pytest-cov=4.1
  - pandera
  - pandera-mypy
  - pydantic
  - python-decouple
  - pip:
    - mariadb=1.1