name: dataLoader
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - pathlib
  - pytest=7.3
  - pytest-mock=3.10
  - pytest-cov=4.1
  - pandera
  - pandera-mypy
  - pydantic=1.10
  - python-decouple
  - pip:
    - mariadb=1.1