name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        # Sets up our anaconda environment
        conda env update --file environment.yml --name base
        # Installs mariadb-server
        sudo apt install mariadb-server
        # Verify version
        mysql -V
        # Installs mariadb python connector
        pip install mariadb
    - name: Test with pytest
      run: pytest
