name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        # Add support for windows-latest
        os: [ubuntu-latest]
        # Add support for '3.7', '3.8', '3.9', '3.10'
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add mariadb to system
      run: |
        # Installs mariadb
        sudo apt install mariadb-server
        sudo apt-get install -y libmariadb-dev
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install python dependencies
      run: |
        # Sets up our anaconda environment
        conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        cd DataWrangling
        pytest
